"""Causal Hybrid Control: hybrid dynamics + a learned causal residual + constrained control.

Current spine (v0.1.0): hybrid dynamics, RK4 rollout, a hand-written discrete adjoint (verified
against autodiff and finite differences), projected-gradient optimal control, MPC, causal
identification behind a pluggable estimator interface, pessimism/support, off-policy evaluation,
and the oracle-regret benchmark.
"""

from __future__ import annotations

from chc.adjoint import control_gradient_adjoint, control_gradient_diffrax, total_cost_diffrax
from chc.causal import (
    ConfoundedLinearSystem,
    dml_point_and_se,
    e_value,
    estimate_control_effect,
    estimate_effect_dml,
    estimate_effect_iv,
    refute_effect,
    sensitivity_analysis,
)
from chc.control import project_box, projected_gradient_control
from chc.cost import QuadraticCost, total_cost
from chc.deep_galerkin import ScalarMLP, solve_poisson_dgm
from chc.did import GroupTimeATT, callaway_santanna, de_chaisemartin, twoway_fixed_effects_att
from chc.discovery import LaggedGraph, TigramiteDiscovery, discover_lagged_parents
from chc.dynamics import DampedOscillator, Dynamics, HybridDynamics, LinearDynamics
from chc.estimators import (
    IV2SLS,
    BackdoorOLS,
    CausalEffectEstimator,
    DoubleML,
    DoWhyEstimator,
    EconMLDoubleML,
    EffectEstimate,
    RLearner,
)
from chc.galerkin import poisson_1d, poisson_2d, thomas_solve
from chc.games import project_simplex, softmax_congestion_equilibrium, stackelberg_allocation
from chc.gmethods import naive_pooled_effect, sequential_g_formula
from chc.independence import partial_corr_test
from chc.integrate import rk4_step, rollout
from chc.irf import (
    innovations,
    irf_control_sequence,
    local_projection_irf,
    structured_irf,
)
from chc.koopman import KoopmanModel, koopman_controller, koopman_lqr_gain
from chc.lqr import (
    continuous_lqr,
    dlqr_feedback_controls,
    finite_horizon_dlqr,
    linearize_continuous,
    linearize_discrete,
    linearized_regret_certificate,
)
from chc.marketplace import (
    ExposureResponse,
    SharedStateMarket,
    calibrate_naive_causal,
    calibrate_predictive,
    calibrate_shared_state,
    interference_bias,
    pessimistic_equilibrium_allocation,
    sutva_allocation,
)
from chc.matching import MarketplaceMatching, SinkhornResult, marketplace_report, sinkhorn
from chc.meanfield import MeanFieldControl
from chc.metrics import overshoot, rise_time, settling_time, steady_state_error
from chc.mintime import (
    BangBangResult,
    bang_bang_control,
    bang_bang_rollout,
    double_integrator_min_time,
    switching_function,
)
from chc.mpc import mpc_control
from chc.network_causal import (
    ConfoundedNetworkSystem,
    NeighbourMessagePassing,
    estimate_network_effects,
    estimate_network_effects_gnn,
)
from chc.offpolicy import GaussianPolicy, fit_behavior_policy, off_policy_value
from chc.pathway import (
    CausalPathway,
    PathwayCertificate,
    PathwayEdge,
    causal_pathway,
    causal_pathway_certificate,
)
from chc.regret import (
    AdaptiveExplorationCurve,
    BanditCausalCurve,
    CausalControlCurve,
    ClusteredLowerBoundCurve,
    CompositionTransferCurve,
    ConfoundedTurnpikeCurve,
    ConfoundingRegretFloorCurve,
    ConfoundingRobustControlCurve,
    ConfoundingRobustLQRegretCurve,
    ConstrainedRegretCurve,
    DoublyRobustCurve,
    DynamicCausalCurve,
    EndToEndC2Curve,
    EnsembleControlCurve,
    ExposureMapCurve,
    FiniteHorizonPLCurve,
    HighProbRegretCurve,
    HInfRobustCurve,
    InformationLowerBoundCurve,
    InterferenceConvexityCurve,
    InterferenceOrthogonalCurve,
    MultiChannelControlCurve,
    MultivariateInterferenceCurve,
    MultivariateTransferCurve,
    NonlinearRegretCurve,
    OptimalExplorationCurve,
    OrthogonalControlCurve,
    PartialIdControlCurve,
    PessimismCurve,
    RegretCurve,
    TransportabilityCurve,
    VanTreesCurve,
    adaptive_exploration_certificate,
    bandit_causal_certificate,
    causal_vs_predictive_certificate,
    certainty_equivalence_control,
    certainty_equivalence_gap,
    closed_loop_cost,
    clustered_lower_bound_certificate,
    composition_transfer_certificate,
    confounded_turnpike_certificate,
    confounding_regret_floor_certificate,
    confounding_robust_control,
    confounding_robust_control_certificate,
    confounding_robust_lq_regret,
    confounding_robust_lq_regret_certificate,
    confounding_robust_lq_regret_matrix,
    constrained_ce_regret_certificate,
    dlqr,
    doubly_robust_control_certificate,
    dynamic_causal_regret_certificate,
    end_to_end_c2_certificate,
    ensemble_control_certificate,
    exposure_map_certificate,
    finite_horizon_pl_certificate,
    highprob_regret_certificate,
    hinf_robust_regret_certificate,
    information_lower_bound_certificate,
    interference_convexity_certificate,
    interference_orthogonal_certificate,
    interference_regret_certificate,
    lq_regret_sensitivity,
    multichannel_control_certificate,
    multivariate_interference_certificate,
    multivariate_transfer_certificate,
    nonlinear_regret_certificate,
    optimal_exploration_certificate,
    orthogonal_control_certificate,
    partial_id_control_certificate,
    pessimism_variance_certificate,
    regret_scaling,
    strong_convexity_regret_bound,
    transportability_regret_certificate,
    van_trees_certificate,
    worst_case_asymmetric_loss,
)
from chc.residual import (
    ContractiveResidual,
    DampingInjectionCertificate,
    GraphResidual,
    KANResidual,
    LipschitzCertificate,
    LipschitzResidual,
    MLPResidual,
    PortHamiltonianCertificate,
    PortHamiltonianResidual,
    ZeroResidual,
    damping_injection_certificate,
    lipschitz_certificate,
    port_hamiltonian_certificate,
)
from chc.scm import SyntheticControlResult, augmented_synthetic_control, synthetic_control
from chc.splitting import (
    exact_linear_flow,
    lie_trotter_step,
    residual_flow,
    strang_marchuk_step,
)
from chc.support import SupportModel, pessimistic_control
from chc.toeplitz import (
    gohberg_semencul_apply,
    gohberg_semencul_covariance,
    gohberg_semencul_generators,
    levinson_durbin,
    sample_autocorrelation,
    solve_toeplitz,
    toeplitz_matvec,
)
from chc.train import fit_residual, fit_residual_multistep, one_step_mse, rollout_mse
from chc.transport import MeanFieldTransport, solve_transport, transport_step
from chc.uncertainty import (
    ConfoundingRobustCertificate,
    ConfoundingRobustClosedLoopCertificate,
    ContractiveRolloutCertificate,
    EnsembleResidual,
    EnsembleUncertainty,
    LipschitzRolloutCertificate,
    SplitConformal,
    TimeVaryingRolloutCertificate,
    WassersteinPenalty,
    certified_horizon,
    closed_loop_rollout_bound,
    confounding_robust_certificate,
    confounding_robust_closed_loop_bound,
    confounding_robust_closed_loop_certificate,
    confounding_robust_inflation,
    confounding_robust_radius,
    constraint_margin,
    contractive_rollout_bound,
    contractive_rollout_certificate,
    fit_ensemble,
    lipschitz_rollout_bound,
    lipschitz_rollout_certificate,
    msm_worst_case_mean,
    support_calibrated_error,
    time_varying_rollout_bound,
    time_varying_rollout_certificate,
)

__version__ = "0.1.0"

__all__ = [
    "IV2SLS",
    "AdaptiveExplorationCurve",
    "BackdoorOLS",
    "BanditCausalCurve",
    "BangBangResult",
    "CausalControlCurve",
    "CausalEffectEstimator",
    "CausalPathway",
    "ClusteredLowerBoundCurve",
    "CompositionTransferCurve",
    "ConfoundedLinearSystem",
    "ConfoundedNetworkSystem",
    "ConfoundedTurnpikeCurve",
    "ConfoundingRegretFloorCurve",
    "ConfoundingRobustCertificate",
    "ConfoundingRobustClosedLoopCertificate",
    "ConfoundingRobustControlCurve",
    "ConfoundingRobustLQRegretCurve",
    "ConstrainedRegretCurve",
    "ContractiveResidual",
    "ContractiveRolloutCertificate",
    "DampedOscillator",
    "DampingInjectionCertificate",
    "DoWhyEstimator",
    "DoubleML",
    "DoublyRobustCurve",
    "DynamicCausalCurve",
    "Dynamics",
    "EconMLDoubleML",
    "EffectEstimate",
    "EndToEndC2Curve",
    "EnsembleControlCurve",
    "EnsembleResidual",
    "EnsembleUncertainty",
    "ExposureMapCurve",
    "ExposureResponse",
    "FiniteHorizonPLCurve",
    "GaussianPolicy",
    "GraphResidual",
    "GroupTimeATT",
    "HInfRobustCurve",
    "HighProbRegretCurve",
    "HybridDynamics",
    "InformationLowerBoundCurve",
    "InterferenceConvexityCurve",
    "InterferenceOrthogonalCurve",
    "KANResidual",
    "KoopmanModel",
    "LaggedGraph",
    "LinearDynamics",
    "LipschitzCertificate",
    "LipschitzResidual",
    "LipschitzRolloutCertificate",
    "MLPResidual",
    "MarketplaceMatching",
    "MeanFieldControl",
    "MeanFieldTransport",
    "MultiChannelControlCurve",
    "MultivariateInterferenceCurve",
    "MultivariateTransferCurve",
    "NeighbourMessagePassing",
    "NonlinearRegretCurve",
    "OptimalExplorationCurve",
    "OrthogonalControlCurve",
    "PartialIdControlCurve",
    "PathwayCertificate",
    "PathwayEdge",
    "PessimismCurve",
    "PortHamiltonianCertificate",
    "PortHamiltonianResidual",
    "QuadraticCost",
    "RLearner",
    "RegretCurve",
    "ScalarMLP",
    "SharedStateMarket",
    "SinkhornResult",
    "SplitConformal",
    "SupportModel",
    "SyntheticControlResult",
    "TigramiteDiscovery",
    "TimeVaryingRolloutCertificate",
    "TransportabilityCurve",
    "VanTreesCurve",
    "WassersteinPenalty",
    "ZeroResidual",
    "__version__",
    "adaptive_exploration_certificate",
    "augmented_synthetic_control",
    "bandit_causal_certificate",
    "bang_bang_control",
    "bang_bang_rollout",
    "calibrate_naive_causal",
    "calibrate_predictive",
    "calibrate_shared_state",
    "callaway_santanna",
    "causal_pathway",
    "causal_pathway_certificate",
    "causal_vs_predictive_certificate",
    "certainty_equivalence_control",
    "certainty_equivalence_gap",
    "certified_horizon",
    "closed_loop_cost",
    "closed_loop_rollout_bound",
    "clustered_lower_bound_certificate",
    "composition_transfer_certificate",
    "confounded_turnpike_certificate",
    "confounding_regret_floor_certificate",
    "confounding_robust_certificate",
    "confounding_robust_closed_loop_bound",
    "confounding_robust_closed_loop_certificate",
    "confounding_robust_control",
    "confounding_robust_control_certificate",
    "confounding_robust_inflation",
    "confounding_robust_lq_regret",
    "confounding_robust_lq_regret_certificate",
    "confounding_robust_lq_regret_matrix",
    "confounding_robust_radius",
    "constrained_ce_regret_certificate",
    "constraint_margin",
    "continuous_lqr",
    "contractive_rollout_bound",
    "contractive_rollout_certificate",
    "control_gradient_adjoint",
    "control_gradient_diffrax",
    "damping_injection_certificate",
    "de_chaisemartin",
    "discover_lagged_parents",
    "dlqr",
    "dlqr_feedback_controls",
    "dml_point_and_se",
    "double_integrator_min_time",
    "doubly_robust_control_certificate",
    "dynamic_causal_regret_certificate",
    "e_value",
    "end_to_end_c2_certificate",
    "ensemble_control_certificate",
    "estimate_control_effect",
    "estimate_effect_dml",
    "estimate_effect_iv",
    "estimate_network_effects",
    "estimate_network_effects_gnn",
    "exact_linear_flow",
    "exposure_map_certificate",
    "finite_horizon_dlqr",
    "finite_horizon_pl_certificate",
    "fit_behavior_policy",
    "fit_ensemble",
    "fit_residual",
    "fit_residual_multistep",
    "gohberg_semencul_apply",
    "gohberg_semencul_covariance",
    "gohberg_semencul_generators",
    "highprob_regret_certificate",
    "hinf_robust_regret_certificate",
    "information_lower_bound_certificate",
    "innovations",
    "interference_bias",
    "interference_convexity_certificate",
    "interference_orthogonal_certificate",
    "interference_regret_certificate",
    "irf_control_sequence",
    "koopman_controller",
    "koopman_lqr_gain",
    "levinson_durbin",
    "lie_trotter_step",
    "linearize_continuous",
    "linearize_discrete",
    "linearized_regret_certificate",
    "lipschitz_certificate",
    "lipschitz_rollout_bound",
    "lipschitz_rollout_certificate",
    "local_projection_irf",
    "lq_regret_sensitivity",
    "marketplace_report",
    "mpc_control",
    "msm_worst_case_mean",
    "multichannel_control_certificate",
    "multivariate_interference_certificate",
    "multivariate_transfer_certificate",
    "naive_pooled_effect",
    "nonlinear_regret_certificate",
    "off_policy_value",
    "one_step_mse",
    "optimal_exploration_certificate",
    "orthogonal_control_certificate",
    "overshoot",
    "partial_corr_test",
    "partial_id_control_certificate",
    "pessimism_variance_certificate",
    "pessimistic_control",
    "pessimistic_equilibrium_allocation",
    "poisson_1d",
    "poisson_2d",
    "port_hamiltonian_certificate",
    "project_box",
    "project_simplex",
    "projected_gradient_control",
    "refute_effect",
    "regret_scaling",
    "residual_flow",
    "rise_time",
    "rk4_step",
    "rollout",
    "rollout_mse",
    "sample_autocorrelation",
    "sensitivity_analysis",
    "sequential_g_formula",
    "settling_time",
    "sinkhorn",
    "softmax_congestion_equilibrium",
    "solve_poisson_dgm",
    "solve_toeplitz",
    "solve_transport",
    "stackelberg_allocation",
    "steady_state_error",
    "strang_marchuk_step",
    "strong_convexity_regret_bound",
    "structured_irf",
    "support_calibrated_error",
    "sutva_allocation",
    "switching_function",
    "synthetic_control",
    "thomas_solve",
    "time_varying_rollout_bound",
    "time_varying_rollout_certificate",
    "toeplitz_matvec",
    "total_cost",
    "total_cost_diffrax",
    "transport_step",
    "transportability_regret_certificate",
    "twoway_fixed_effects_att",
    "van_trees_certificate",
    "worst_case_asymmetric_loss",
]
