"""Causal Hybrid Control: hybrid dynamics + a learned causal residual + constrained control.

The spine: hybrid dynamics, RK4 rollout, a hand-written discrete adjoint (verified
against autodiff and finite differences), projected-gradient optimal control, MPC, causal
identification behind a pluggable estimator interface, pessimism/support, off-policy evaluation,
and the oracle-regret benchmark. On top of it: control under hidden confounding, the safety
layer that spends the identification radius on a constraint, and `chc.spine`, which runs the
whole chain -- confounded logs to certified plan -- as one decision.

Two distinctions the API deliberately keeps visible rather than smoothing over. Fitting a residual
by prediction error is not identifying it: under a confounded logging policy that recovers the
observational control response, and `chc.dynamics_id` is the module that recovers the interventional
one. And "safety" names three different operations -- **plan** (`causal_plan`, which holds a
barrier in the solve only when handed one), **audit** (`certify_safety`, read-only), **filter**
(`robust_safety_filter`, one action at a time) -- and the audit's verdict is the one to read, even
on a plan solved under the barrier; see `chc.plan` for what each does and does not promise.

The top level holds the lifecycle's names (`docs/lifecycle.md`), the classes a call to one of them
takes, and the errors they raise. Every other name lives at its module path; one that 0.7.0 bound
here still imports from it, with a `DeprecationWarning` naming the module, until 1.0.
"""

from __future__ import annotations

import importlib as _importlib
import warnings as _warnings
from typing import TYPE_CHECKING

# Every module a top-level name came from is imported, as it was when the top level bound every
# name, so that `import chc` followed by `chc.<module>.<name>` keeps working.
# isort: off
from chc import (
    adjoint as adjoint,
    barrier as barrier,
    causal as causal,
    control as control,
    cost as cost,
    decision as decision,
    deep_galerkin as deep_galerkin,
    delay as delay,
    did as did,
    discovery as discovery,
    dynamics as dynamics,
    dynamics_id as dynamics_id,
    estimators as estimators,
    evaluation as evaluation,
    experiment as experiment,
    frames as frames,
    galerkin as galerkin,
    games as games,
    gate as gate,
    gmethods as gmethods,
    graph as graph,
    independence as independence,
    integrate as integrate,
    irf as irf,
    koopman as koopman,
    lqr as lqr,
    marketplace as marketplace,
    matching as matching,
    meanfield as meanfield,
    metrics as metrics,
    mintime as mintime,
    mmm as mmm,
    mpc as mpc,
    network_causal as network_causal,
    offpolicy as offpolicy,
    panel as panel,
    pathway as pathway,
    plan as plan,
    reachability as reachability,
    regret as regret,
    residual as residual,
    scm as scm,
    splitting as splitting,
    support as support,
    switchback as switchback,
    symbolic as symbolic,
    toeplitz as toeplitz,
    train as train,
    transport as transport,
    uncertainty as uncertainty,
)

# isort: on
from chc.barrier import robust_safety_filter
from chc.causal import e_value, estimate_effect_dml, refute_effect, sensitivity_analysis
from chc.control import LinearConstraint
from chc.cost import QuadraticCost
from chc.decision import (
    Constraint,
    DecisionError,
    Driver,
    Lever,
    NotIdentifiedError,
    Target,
    prescribe,
)
from chc.dynamics import HybridDynamics
from chc.dynamics_id import fit_causal_residual
from chc.evaluation import (
    AffinePolicy,
    InfeasibleEvaluation,
    InitialLaw,
    LinearGaussianPlant,
    certify_evaluation,
    evaluate_plan,
)
from chc.experiment import ChannelPrior, ZoneDecision, ZoneExperiment, design_experiment
from chc.gate import DecisionLog, DeploymentGate, GateConfig, ZoneBatch, ZonePlan
from chc.graph import CausalGraph, CyclicGraphError
from chc.irf import delay_estimate
from chc.matching import shadow_price_effect, shadow_price_interval
from chc.mpc import PeriodBudget, RecedingHorizon
from chc.offpolicy import GaussianPolicy, off_policy_value
from chc.panel import Panel, PanelError, Provenance
from chc.panel import installed_version as _installed_version
from chc.plan import BarrierConstraint, CausalPlan, causal_plan, certify_safety, plan_regret_bound
from chc.regret import (
    adaptive_exploration_certificate,
    capped_exploration_policy,
    minimax_action,
    optimal_exploration_certificate,
)
from chc.support import SupportModel
from chc.switchback import (
    BlockDesign,
    Horizon,
    PersistencePrior,
    TargetMDE,
    design_switchback,
    read_switchback,
)
from chc.uncertainty import SplitConformal

__version__ = _installed_version()
"""The installed distribution's version. See :func:`chc.panel.installed_version`."""

__all__ = [
    "AffinePolicy",
    "BarrierConstraint",
    "BlockDesign",
    "CausalGraph",
    "CausalPlan",
    "ChannelPrior",
    "Constraint",
    "CyclicGraphError",
    "DecisionError",
    "DecisionLog",
    "DeploymentGate",
    "Driver",
    "GateConfig",
    "GaussianPolicy",
    "Horizon",
    "HybridDynamics",
    "InfeasibleEvaluation",
    "InitialLaw",
    "Lever",
    "LinearConstraint",
    "LinearGaussianPlant",
    "NotIdentifiedError",
    "Panel",
    "PanelError",
    "PeriodBudget",
    "PersistencePrior",
    "Provenance",
    "QuadraticCost",
    "RecedingHorizon",
    "SplitConformal",
    "SupportModel",
    "Target",
    "TargetMDE",
    "ZoneBatch",
    "ZoneDecision",
    "ZoneExperiment",
    "ZonePlan",
    "__version__",
    "adaptive_exploration_certificate",
    "capped_exploration_policy",
    "causal_plan",
    "certify_evaluation",
    "certify_safety",
    "delay_estimate",
    "design_experiment",
    "design_switchback",
    "e_value",
    "estimate_effect_dml",
    "evaluate_plan",
    "fit_causal_residual",
    "minimax_action",
    "off_policy_value",
    "optimal_exploration_certificate",
    "plan_regret_bound",
    "prescribe",
    "read_switchback",
    "refute_effect",
    "robust_safety_filter",
    "sensitivity_analysis",
    "shadow_price_effect",
    "shadow_price_interval",
]

# Every other name 0.7.0 bound here, and the module it lives in, where it stays. Each is
# served from the module with a DeprecationWarning until 1.0 (docs/adr/0016).
_MOVED: dict[str, str] = {
    "AdaptiveExplorationCurve": "chc.regret",
    "adjoint_weighted_error": "chc.deep_galerkin",
    "AdjustmentSet": "chc.graph",
    "AdjustmentStatus": "chc.graph",
    "admissible_action_interval": "chc.barrier",
    "adstock_dynamics": "chc.mmm",
    "advection_diffusion_field": "chc.transport",
    "advection_diffusion_kernel": "chc.transport",
    "advection_diffusion_propagator": "chc.transport",
    "advection_diffusion_symbol": "chc.transport",
    "as_columns": "chc.frames",
    "asymmetric_control_improvement": "chc.regret",
    "augment_state": "chc.delay",
    "augmented_synthetic_control": "chc.scm",
    "BackdoorOLS": "chc.estimators",
    "backward_reachable_tube": "chc.reachability",
    "bandit_causal_certificate": "chc.regret",
    "BanditCausalCurve": "chc.regret",
    "bang_bang_control": "chc.mintime",
    "bang_bang_rollout": "chc.mintime",
    "BangBangResult": "chc.mintime",
    "barrier_confounding_certificate": "chc.barrier",
    "barrier_gamma_star": "chc.barrier",
    "barrier_reachability_gap": "chc.reachability",
    "BarrierConfoundingCurve": "chc.barrier",
    "BarrierReachabilityGap": "chc.reachability",
    "benchmark_gamma": "chc.uncertainty",
    "BlindnessSweep": "chc.deep_galerkin",
    "Bound": "chc.control",
    "box_stationarity": "chc.control",
    "calibrate_naive_causal": "chc.marketplace",
    "calibrate_predictive": "chc.marketplace",
    "calibrate_shared_state": "chc.marketplace",
    "callaway_santanna": "chc.did",
    "CappedExplorationPolicy": "chc.regret",
    "causal_pathway": "chc.pathway",
    "causal_pathway_certificate": "chc.pathway",
    "causal_vs_predictive_certificate": "chc.regret",
    "CausalControlCurve": "chc.regret",
    "CausalDynamicsFit": "chc.dynamics_id",
    "CausalEffectEstimator": "chc.estimators",
    "CausalPathway": "chc.pathway",
    "ce_explicit_constant_certificate": "chc.regret",
    "CeExplicitConstantCurve": "chc.regret",
    "certainty_equivalence_control": "chc.regret",
    "certainty_equivalence_gap": "chc.regret",
    "CertificateStatus": "chc.plan",
    "certified_horizon": "chc.uncertainty",
    "circulant_matvec": "chc.toeplitz",
    "circulant_operator_norm": "chc.toeplitz",
    "circulant_symbol": "chc.toeplitz",
    "closed_loop_attribution_certificate": "chc.dynamics_id",
    "closed_loop_cost": "chc.regret",
    "closed_loop_gain_attribution": "chc.dynamics_id",
    "closed_loop_rollout_bound": "chc.uncertainty",
    "ClosedLoopAttribution": "chc.dynamics_id",
    "ClosedLoopAttributionCertificate": "chc.dynamics_id",
    "cluster_fold_leakage_certificate": "chc.regret",
    "clustered_lower_bound_certificate": "chc.regret",
    "ClusteredLowerBoundCurve": "chc.regret",
    "ColumnData": "chc.frames",
    "ColumnFrame": "chc.frames",
    "composition_transfer_certificate": "chc.regret",
    "CompositionTransferCurve": "chc.regret",
    "confounded_turnpike_certificate": "chc.regret",
    "ConfoundedControlAffineSystem": "chc.dynamics_id",
    "ConfoundedLinearSystem": "chc.causal",
    "ConfoundedNetworkSystem": "chc.network_causal",
    "ConfoundedTurnpikeCurve": "chc.regret",
    "confounding_cost_bound_certificate": "chc.uncertainty",
    "confounding_regret_floor_certificate": "chc.regret",
    "confounding_robust_certificate": "chc.uncertainty",
    "confounding_robust_closed_loop_bound": "chc.uncertainty",
    "confounding_robust_closed_loop_certificate": "chc.uncertainty",
    "confounding_robust_control": "chc.regret",
    "confounding_robust_control_benchmark": "chc.regret",
    "confounding_robust_control_certificate": "chc.regret",
    "confounding_robust_inflation": "chc.uncertainty",
    "confounding_robust_lq_regret": "chc.regret",
    "confounding_robust_lq_regret_certificate": "chc.regret",
    "confounding_robust_lq_regret_matrix": "chc.regret",
    "confounding_robust_radius": "chc.uncertainty",
    "confounding_robust_tracking_benchmark": "chc.regret",
    "confounding_robust_tracking_loop": "chc.regret",
    "ConfoundingBoundCurve": "chc.uncertainty",
    "ConfoundingRegretFloorCurve": "chc.regret",
    "ConfoundingRobustCertificate": "chc.uncertainty",
    "ConfoundingRobustClosedLoopCertificate": "chc.uncertainty",
    "ConfoundingRobustControlCurve": "chc.regret",
    "ConfoundingRobustLQRegretCurve": "chc.regret",
    "ConfoundingRobustPenalty": "chc.uncertainty",
    "CongestedMeanFieldGame": "chc.deep_galerkin",
    "congestion_contraction_certificate": "chc.games",
    "congestion_contraction_modulus": "chc.games",
    "congestion_damping": "chc.games",
    "CongestionContractionCertificate": "chc.games",
    "conjugate_time_certificate": "chc.regret",
    "ConjugateTimeCurve": "chc.regret",
    "constrained_ce_regret_certificate": "chc.regret",
    "ConstrainedRegretCurve": "chc.regret",
    "constraint_margin": "chc.uncertainty",
    "continuous_lqr": "chc.lqr",
    "contractive_rollout_bound": "chc.uncertainty",
    "contractive_rollout_certificate": "chc.uncertainty",
    "ContractiveResidual": "chc.residual",
    "ContractiveRolloutCertificate": "chc.uncertainty",
    "control_affine_features": "chc.residual",
    "control_channel": "chc.barrier",
    "control_gradient_adjoint": "chc.adjoint",
    "control_gradient_diffrax": "chc.adjoint",
    "ControlAffineResidual": "chc.residual",
    "convection_diffusion_1d": "chc.galerkin",
    "convection_diffusion_certificate": "chc.galerkin",
    "convection_diffusion_exact": "chc.galerkin",
    "ConvectionDiffusionCurve": "chc.galerkin",
    "convex_energy_certificate": "chc.residual",
    "ConvexEnergyCertificate": "chc.residual",
    "costate_norms": "chc.adjoint",
    "cross_cluster_mixing_certificate": "chc.regret",
    "CrossClusterMixingCurve": "chc.regret",
    "cvar_upper": "chc.uncertainty",
    "DampedOscillator": "chc.dynamics",
    "damping_injection_certificate": "chc.residual",
    "DampingInjectionCertificate": "chc.residual",
    "de_chaisemartin": "chc.did",
    "DecisionCertificate": "chc.decision",
    "delay_ball": "chc.delay",
    "delay_ball_certificate": "chc.delay",
    "delay_design_loss": "chc.delay",
    "delay_margin": "chc.delay",
    "delay_margin_certificate": "chc.delay",
    "DelayBall": "chc.delay",
    "DelayBallCertificate": "chc.delay",
    "delayed_network_certificate": "chc.regret",
    "delayed_of": "chc.delay",
    "DelayedDynamics": "chc.delay",
    "DelayedNetworkPanel": "chc.network_causal",
    "DelayEstimate": "chc.irf",
    "DelayMarginCertificate": "chc.delay",
    "discover_lagged_parents": "chc.discovery",
    "dlqr": "chc.regret",
    "dlqr_feedback_controls": "chc.lqr",
    "dml_point_and_se": "chc.causal",
    "double_integrator_min_time": "chc.mintime",
    "DoubleML": "chc.estimators",
    "doubly_robust_control_certificate": "chc.regret",
    "DoublyRobustCurve": "chc.regret",
    "DoWhyEstimator": "chc.estimators",
    "DrivenDynamics": "chc.dynamics",
    "dual_weighted_error_estimate": "chc.deep_galerkin",
    "dynamic_causal_regret_certificate": "chc.regret",
    "DynamicCausalCurve": "chc.regret",
    "DynamicConfoundingCurve": "chc.regret",
    "Dynamics": "chc.dynamics",
    "EconMLDoubleML": "chc.estimators",
    "EffectEstimate": "chc.estimators",
    "end_to_end_c2_certificate": "chc.regret",
    "EndToEndC2Curve": "chc.regret",
    "ensemble_control_certificate": "chc.regret",
    "EnsembleControlCurve": "chc.regret",
    "EnsembleResidual": "chc.uncertainty",
    "EnsembleUncertainty": "chc.uncertainty",
    "equilibrium_monotonicity_certificate": "chc.games",
    "equilibrium_transfer_certificate": "chc.games",
    "EquilibriumMonotonicityCertificate": "chc.games",
    "EquilibriumSolution": "chc.games",
    "EquilibriumTransferCertificate": "chc.games",
    "estimate_control_effect": "chc.causal",
    "estimate_effect_iv": "chc.causal",
    "estimate_network_effects": "chc.network_causal",
    "estimate_network_effects_gnn": "chc.network_causal",
    "estimate_propagation": "chc.network_causal",
    "exact_delayed_rollout": "chc.delay",
    "exact_linear_flow": "chc.splitting",
    "exact_matrix_ratio_moment": "chc.regret",
    "exact_ratio_moment": "chc.regret",
    "exposure_map_certificate": "chc.regret",
    "ExposureMapCurve": "chc.regret",
    "ExposureResponse": "chc.marketplace",
    "extract_symbolic": "chc.symbolic",
    "extract_symbolic_edge": "chc.symbolic",
    "FieldMLP": "chc.deep_galerkin",
    "finite_horizon_dlqr": "chc.lqr",
    "finite_horizon_pl_certificate": "chc.regret",
    "finite_population_gap_certificate": "chc.deep_galerkin",
    "FiniteHorizonPLCurve": "chc.regret",
    "FinitePopulationGap": "chc.deep_galerkin",
    "fit_behavior_policy": "chc.offpolicy",
    "fit_ensemble": "chc.uncertainty",
    "fit_residual": "chc.train",
    "fit_residual_multistep": "chc.train",
    "fit_spectral_residual": "chc.residual",
    "fixed_point": "chc.games",
    "fold_exactness_certificate": "chc.regret",
    "fold_heuristic_certificate": "chc.regret",
    "FoldDesign": "chc.regret",
    "FoldExactnessCurve": "chc.regret",
    "FoldHeuristicCurve": "chc.regret",
    "gamma_benchmark_certificate": "chc.uncertainty",
    "GammaBenchmark": "chc.uncertainty",
    "GammaBenchmarkCertificate": "chc.uncertainty",
    "gohberg_semencul_apply": "chc.toeplitz",
    "gohberg_semencul_covariance": "chc.toeplitz",
    "gohberg_semencul_generators": "chc.toeplitz",
    "graph_shells": "chc.network_causal",
    "GraphResidual": "chc.residual",
    "GroupTimeATT": "chc.did",
    "higher_order_barrier_gap": "chc.reachability",
    "HigherOrderBarrierGap": "chc.reachability",
    "highprob_regret_certificate": "chc.regret",
    "HighProbRegretCurve": "chc.regret",
    "hinf_robust_regret_certificate": "chc.regret",
    "HInfRobustCurve": "chc.regret",
    "identification_radius_threshold": "chc.barrier",
    "IdentificationStatus": "chc.decision",
    "information_lower_bound_certificate": "chc.regret",
    "InformationLowerBoundCurve": "chc.regret",
    "innovations": "chc.irf",
    "installed_version": "chc.panel",
    "interference_bias": "chc.marketplace",
    "interference_convexity_certificate": "chc.regret",
    "interference_orthogonal_certificate": "chc.regret",
    "interference_regret_certificate": "chc.regret",
    "InterferenceConvexityCurve": "chc.regret",
    "InterferenceOrthogonalCurve": "chc.regret",
    "InterventionSchedule": "chc.decision",
    "irf_control_sequence": "chc.irf",
    "IV2SLS": "chc.estimators",
    "kan_edge": "chc.symbolic",
    "KANResidual": "chc.residual",
    "koopman_controller": "chc.koopman",
    "koopman_lqr_gain": "chc.koopman",
    "KoopmanModel": "chc.koopman",
    "kronecker_spectrum": "chc.network_causal",
    "LaggedGraph": "chc.discovery",
    "lbfgs_box_control": "chc.control",
    "LeverSelection": "chc.decision",
    "levinson_durbin": "chc.toeplitz",
    "LIBRARY": "chc.symbolic",
    "lie_trotter_step": "chc.splitting",
    "lift_cost": "chc.delay",
    "LinearDynamics": "chc.dynamics",
    "linearize_continuous": "chc.lqr",
    "linearize_discrete": "chc.lqr",
    "linearized_regret_certificate": "chc.lqr",
    "lipschitz_certificate": "chc.residual",
    "lipschitz_rollout_bound": "chc.uncertainty",
    "lipschitz_rollout_certificate": "chc.uncertainty",
    "LipschitzCertificate": "chc.residual",
    "LipschitzResidual": "chc.residual",
    "LipschitzRolloutCertificate": "chc.uncertainty",
    "local_projection_irf": "chc.irf",
    "lq_mean_field_certificate": "chc.deep_galerkin",
    "lq_regret_sensitivity": "chc.regret",
    "LQMeanFieldGame": "chc.deep_galerkin",
    "MarketingMixPlant": "chc.mmm",
    "MarketingMixSystem": "chc.mmm",
    "marketplace_report": "chc.matching",
    "MarketplaceControlCurve": "chc.regret",
    "MarketplaceMatching": "chc.matching",
    "matrix_ratio_certificate": "chc.regret",
    "max_stages": "chc.delay",
    "MeanFieldControl": "chc.meanfield",
    "MeanFieldCurve": "chc.deep_galerkin",
    "MeanFieldDGM": "chc.deep_galerkin",
    "MeanFieldOptimizer": "chc.deep_galerkin",
    "MeanFieldSolution": "chc.deep_galerkin",
    "MeanFieldTransport": "chc.transport",
    "minimax_exploration_certificate": "chc.regret",
    "minimax_lq_certificate": "chc.regret",
    "minimax_lq_policy": "chc.regret",
    "MinimaxAction": "chc.regret",
    "MinimaxBranch": "chc.regret",
    "MinimaxCriterion": "chc.regret",
    "MinimaxLQCertificate": "chc.regret",
    "MinimaxLQPolicy": "chc.regret",
    "MLPResidual": "chc.residual",
    "MmmArm": "chc.mmm",
    "MmmReport": "chc.mmm",
    "ModulusSource": "chc.plan",
    "mpc_control": "chc.mpc",
    "msm_worst_case_mean": "chc.uncertainty",
    "multichannel_control_certificate": "chc.regret",
    "MultiChannelControlCurve": "chc.regret",
    "multivariate_action_floor": "chc.regret",
    "multivariate_interference_certificate": "chc.regret",
    "multivariate_transfer_certificate": "chc.regret",
    "multivariate_van_trees_certificate": "chc.regret",
    "MultivariateActionFloor": "chc.regret",
    "MultivariateInterferenceCurve": "chc.regret",
    "MultivariateTransferCurve": "chc.regret",
    "MultivariateVanTreesCurve": "chc.regret",
    "naive_pooled_effect": "chc.gmethods",
    "negative_control_gamma": "chc.uncertainty",
    "NeighbourMessagePassing": "chc.network_causal",
    "NestedCVaRPenalty": "chc.uncertainty",
    "NestedRiskCertificate": "chc.uncertainty",
    "nlp_solver_certificate": "chc.control",
    "NLPSolverCertificate": "chc.control",
    "nonlinear_dwr_certificate": "chc.deep_galerkin",
    "nonlinear_regret_certificate": "chc.regret",
    "NonlinearDwrCurve": "chc.deep_galerkin",
    "NonlinearRegretCurve": "chc.regret",
    "one_step_mse": "chc.train",
    "optimal_delay_gain": "chc.delay",
    "optimal_fold_partition": "chc.regret",
    "optimal_upwind": "chc.galerkin",
    "OptimalExplorationCurve": "chc.regret",
    "orthogonal_control_certificate": "chc.regret",
    "OrthogonalControlCurve": "chc.regret",
    "overshoot": "chc.metrics",
    "panel_covariance": "chc.network_causal",
    "panel_estimator_certificate": "chc.regret",
    "PanelEstimatorGate": "chc.regret",
    "partial_corr_test": "chc.independence",
    "partial_id_control_certificate": "chc.regret",
    "PartialIdControlCurve": "chc.regret",
    "PathwayCertificate": "chc.pathway",
    "PathwayEdge": "chc.pathway",
    "peak_lag": "chc.irf",
    "periodic_smoothing_kernel": "chc.transport",
    "periodic_wavenumbers": "chc.transport",
    "perturbation_cost_weights": "chc.adjoint",
    "pessimism_variance_certificate": "chc.regret",
    "PessimismCurve": "chc.regret",
    "pessimistic_control": "chc.support",
    "pessimistic_equilibrium_allocation": "chc.marketplace",
    "pessimistic_solve": "chc.support",
    "PlanRegretBound": "chc.plan",
    "poisson_1d": "chc.galerkin",
    "poisson_2d": "chc.galerkin",
    "PopulationNoise": "chc.deep_galerkin",
    "port_hamiltonian_certificate": "chc.residual",
    "PortHamiltonianCertificate": "chc.residual",
    "PortHamiltonianEnergy": "chc.residual",
    "PortHamiltonianResidual": "chc.residual",
    "Prescription": "chc.decision",
    "PriceStatus": "chc.plan",
    "project_box": "chc.control",
    "project_simplex": "chc.games",
    "projected_gradient_control": "chc.control",
    "projected_gradient_solve": "chc.control",
    "ReachableTube": "chc.reachability",
    "regret_scaling": "chc.regret",
    "RegretCurve": "chc.regret",
    "residual_blindness_sweep": "chc.deep_galerkin",
    "residual_flow": "chc.splitting",
    "rise_time": "chc.metrics",
    "rk4_step": "chc.integrate",
    "RLearner": "chc.estimators",
    "robust_barrier_margin": "chc.barrier",
    "robust_delay_design": "chc.delay",
    "robust_hamiltonian": "chc.reachability",
    "robust_safe_action": "chc.barrier",
    "RobustDelayDesign": "chc.delay",
    "rollout": "chc.integrate",
    "rollout_mse": "chc.train",
    "RowPrice": "chc.plan",
    "run_marketing_mix": "chc.mmm",
    "safety_filter_benchmark": "chc.barrier",
    "SafetyCertificate": "chc.plan",
    "SafetyFilterBenchmark": "chc.barrier",
    "sample_autocorrelation": "chc.toeplitz",
    "ScalarMLP": "chc.deep_galerkin",
    "SelectionStep": "chc.decision",
    "sequential_g_formula": "chc.gmethods",
    "settling_time": "chc.metrics",
    "ShadowPrices": "chc.plan",
    "sharded_ensemble_certificate": "chc.uncertainty",
    "ShardedEnsembleCertificate": "chc.uncertainty",
    "SharedStateMarket": "chc.marketplace",
    "sinkhorn": "chc.matching",
    "SinkhornResult": "chc.matching",
    "softmax_congestion_equilibrium": "chc.games",
    "solve_channel_moment": "chc.dynamics_id",
    "solve_mfg_dgm": "chc.deep_galerkin",
    "solve_poisson_dgm": "chc.deep_galerkin",
    "solve_toeplitz": "chc.toeplitz",
    "solve_transport": "chc.transport",
    "SolverComparison": "chc.control",
    "SolverResult": "chc.control",
    "SolverStatus": "chc.control",
    "space_time_fold_certificate": "chc.regret",
    "SpaceTimeFoldCurve": "chc.regret",
    "spectral_residual_certificate": "chc.residual",
    "SpectralResidual": "chc.residual",
    "SpectralResidualCurve": "chc.residual",
    "stackelberg_allocation": "chc.games",
    "stages_for_spread": "chc.delay",
    "state_of": "chc.delay",
    "state_trajectory": "chc.delay",
    "steady_state_error": "chc.metrics",
    "strang_marchuk_step": "chc.splitting",
    "strong_convexity_regret_bound": "chc.regret",
    "structured_irf": "chc.irf",
    "support_calibrated_error": "chc.uncertainty",
    "sutva_allocation": "chc.marketplace",
    "switching_function": "chc.mintime",
    "symbolic_extraction_certificate": "chc.symbolic",
    "SymbolicEdge": "chc.symbolic",
    "SymbolicExtractionCurve": "chc.symbolic",
    "synthetic_control": "chc.scm",
    "SyntheticControlResult": "chc.scm",
    "thomas_solve": "chc.galerkin",
    "TigramiteDiscovery": "chc.discovery",
    "time_varying_rollout_bound": "chc.uncertainty",
    "time_varying_rollout_certificate": "chc.uncertainty",
    "TimeVaryingRolloutCertificate": "chc.uncertainty",
    "toeplitz_matvec": "chc.toeplitz",
    "torus_adjacency": "chc.network_causal",
    "total_cost": "chc.cost",
    "total_cost_diffrax": "chc.adjoint",
    "transport_step": "chc.transport",
    "transportability_regret_certificate": "chc.regret",
    "TransportabilityCurve": "chc.regret",
    "twoway_fixed_effects_att": "chc.did",
    "van_trees_certificate": "chc.regret",
    "VanTreesCurve": "chc.regret",
    "WassersteinPenalty": "chc.uncertainty",
    "worst_case_asymmetric_loss": "chc.regret",
    "ZeroResidual": "chc.residual",
}

if TYPE_CHECKING:
    # The same names, bound for type checkers only: a checked caller is warned at run time, not
    # broken at check time, while the deprecation lasts. `x as x` marks each as re-exported.
    # isort: off
    from chc.adjoint import (
        control_gradient_adjoint as control_gradient_adjoint,
        control_gradient_diffrax as control_gradient_diffrax,
        costate_norms as costate_norms,
        perturbation_cost_weights as perturbation_cost_weights,
        total_cost_diffrax as total_cost_diffrax,
    )
    from chc.barrier import (
        admissible_action_interval as admissible_action_interval,
        barrier_confounding_certificate as barrier_confounding_certificate,
        barrier_gamma_star as barrier_gamma_star,
        BarrierConfoundingCurve as BarrierConfoundingCurve,
        control_channel as control_channel,
        identification_radius_threshold as identification_radius_threshold,
        robust_barrier_margin as robust_barrier_margin,
        robust_safe_action as robust_safe_action,
        safety_filter_benchmark as safety_filter_benchmark,
        SafetyFilterBenchmark as SafetyFilterBenchmark,
    )
    from chc.causal import (
        ConfoundedLinearSystem as ConfoundedLinearSystem,
        dml_point_and_se as dml_point_and_se,
        estimate_control_effect as estimate_control_effect,
        estimate_effect_iv as estimate_effect_iv,
    )
    from chc.control import (
        Bound as Bound,
        box_stationarity as box_stationarity,
        lbfgs_box_control as lbfgs_box_control,
        nlp_solver_certificate as nlp_solver_certificate,
        NLPSolverCertificate as NLPSolverCertificate,
        project_box as project_box,
        projected_gradient_control as projected_gradient_control,
        projected_gradient_solve as projected_gradient_solve,
        SolverComparison as SolverComparison,
        SolverResult as SolverResult,
        SolverStatus as SolverStatus,
    )
    from chc.cost import total_cost as total_cost
    from chc.decision import (
        DecisionCertificate as DecisionCertificate,
        IdentificationStatus as IdentificationStatus,
        InterventionSchedule as InterventionSchedule,
        LeverSelection as LeverSelection,
        Prescription as Prescription,
        SelectionStep as SelectionStep,
    )
    from chc.deep_galerkin import (
        adjoint_weighted_error as adjoint_weighted_error,
        BlindnessSweep as BlindnessSweep,
        CongestedMeanFieldGame as CongestedMeanFieldGame,
        dual_weighted_error_estimate as dual_weighted_error_estimate,
        FieldMLP as FieldMLP,
        finite_population_gap_certificate as finite_population_gap_certificate,
        FinitePopulationGap as FinitePopulationGap,
        lq_mean_field_certificate as lq_mean_field_certificate,
        LQMeanFieldGame as LQMeanFieldGame,
        MeanFieldCurve as MeanFieldCurve,
        MeanFieldDGM as MeanFieldDGM,
        MeanFieldOptimizer as MeanFieldOptimizer,
        MeanFieldSolution as MeanFieldSolution,
        nonlinear_dwr_certificate as nonlinear_dwr_certificate,
        NonlinearDwrCurve as NonlinearDwrCurve,
        PopulationNoise as PopulationNoise,
        residual_blindness_sweep as residual_blindness_sweep,
        ScalarMLP as ScalarMLP,
        solve_mfg_dgm as solve_mfg_dgm,
        solve_poisson_dgm as solve_poisson_dgm,
    )
    from chc.delay import (
        augment_state as augment_state,
        delay_ball as delay_ball,
        delay_ball_certificate as delay_ball_certificate,
        delay_design_loss as delay_design_loss,
        delay_margin as delay_margin,
        delay_margin_certificate as delay_margin_certificate,
        DelayBall as DelayBall,
        DelayBallCertificate as DelayBallCertificate,
        delayed_of as delayed_of,
        DelayedDynamics as DelayedDynamics,
        DelayMarginCertificate as DelayMarginCertificate,
        exact_delayed_rollout as exact_delayed_rollout,
        lift_cost as lift_cost,
        max_stages as max_stages,
        optimal_delay_gain as optimal_delay_gain,
        robust_delay_design as robust_delay_design,
        RobustDelayDesign as RobustDelayDesign,
        stages_for_spread as stages_for_spread,
        state_of as state_of,
        state_trajectory as state_trajectory,
    )
    from chc.did import (
        callaway_santanna as callaway_santanna,
        de_chaisemartin as de_chaisemartin,
        GroupTimeATT as GroupTimeATT,
        twoway_fixed_effects_att as twoway_fixed_effects_att,
    )
    from chc.discovery import (
        discover_lagged_parents as discover_lagged_parents,
        LaggedGraph as LaggedGraph,
        TigramiteDiscovery as TigramiteDiscovery,
    )
    from chc.dynamics import (
        DampedOscillator as DampedOscillator,
        DrivenDynamics as DrivenDynamics,
        Dynamics as Dynamics,
        LinearDynamics as LinearDynamics,
    )
    from chc.dynamics_id import (
        CausalDynamicsFit as CausalDynamicsFit,
        closed_loop_attribution_certificate as closed_loop_attribution_certificate,
        closed_loop_gain_attribution as closed_loop_gain_attribution,
        ClosedLoopAttribution as ClosedLoopAttribution,
        ClosedLoopAttributionCertificate as ClosedLoopAttributionCertificate,
        ConfoundedControlAffineSystem as ConfoundedControlAffineSystem,
        solve_channel_moment as solve_channel_moment,
    )
    from chc.estimators import (
        BackdoorOLS as BackdoorOLS,
        CausalEffectEstimator as CausalEffectEstimator,
        DoubleML as DoubleML,
        DoWhyEstimator as DoWhyEstimator,
        EconMLDoubleML as EconMLDoubleML,
        EffectEstimate as EffectEstimate,
        IV2SLS as IV2SLS,
        RLearner as RLearner,
    )
    from chc.frames import (
        as_columns as as_columns,
        ColumnData as ColumnData,
        ColumnFrame as ColumnFrame,
    )
    from chc.galerkin import (
        convection_diffusion_1d as convection_diffusion_1d,
        convection_diffusion_certificate as convection_diffusion_certificate,
        convection_diffusion_exact as convection_diffusion_exact,
        ConvectionDiffusionCurve as ConvectionDiffusionCurve,
        optimal_upwind as optimal_upwind,
        poisson_1d as poisson_1d,
        poisson_2d as poisson_2d,
        thomas_solve as thomas_solve,
    )
    from chc.games import (
        congestion_contraction_certificate as congestion_contraction_certificate,
        congestion_contraction_modulus as congestion_contraction_modulus,
        congestion_damping as congestion_damping,
        CongestionContractionCertificate as CongestionContractionCertificate,
        equilibrium_monotonicity_certificate as equilibrium_monotonicity_certificate,
        equilibrium_transfer_certificate as equilibrium_transfer_certificate,
        EquilibriumMonotonicityCertificate as EquilibriumMonotonicityCertificate,
        EquilibriumSolution as EquilibriumSolution,
        EquilibriumTransferCertificate as EquilibriumTransferCertificate,
        fixed_point as fixed_point,
        project_simplex as project_simplex,
        softmax_congestion_equilibrium as softmax_congestion_equilibrium,
        stackelberg_allocation as stackelberg_allocation,
    )
    from chc.gmethods import (
        naive_pooled_effect as naive_pooled_effect,
        sequential_g_formula as sequential_g_formula,
    )
    from chc.graph import AdjustmentSet as AdjustmentSet, AdjustmentStatus as AdjustmentStatus
    from chc.independence import partial_corr_test as partial_corr_test
    from chc.integrate import rk4_step as rk4_step, rollout as rollout
    from chc.irf import (
        DelayEstimate as DelayEstimate,
        innovations as innovations,
        irf_control_sequence as irf_control_sequence,
        local_projection_irf as local_projection_irf,
        peak_lag as peak_lag,
        structured_irf as structured_irf,
    )
    from chc.koopman import (
        koopman_controller as koopman_controller,
        koopman_lqr_gain as koopman_lqr_gain,
        KoopmanModel as KoopmanModel,
    )
    from chc.lqr import (
        continuous_lqr as continuous_lqr,
        dlqr_feedback_controls as dlqr_feedback_controls,
        finite_horizon_dlqr as finite_horizon_dlqr,
        linearize_continuous as linearize_continuous,
        linearize_discrete as linearize_discrete,
        linearized_regret_certificate as linearized_regret_certificate,
    )
    from chc.marketplace import (
        calibrate_naive_causal as calibrate_naive_causal,
        calibrate_predictive as calibrate_predictive,
        calibrate_shared_state as calibrate_shared_state,
        ExposureResponse as ExposureResponse,
        interference_bias as interference_bias,
        pessimistic_equilibrium_allocation as pessimistic_equilibrium_allocation,
        SharedStateMarket as SharedStateMarket,
        sutva_allocation as sutva_allocation,
    )
    from chc.matching import (
        marketplace_report as marketplace_report,
        MarketplaceMatching as MarketplaceMatching,
        sinkhorn as sinkhorn,
        SinkhornResult as SinkhornResult,
    )
    from chc.meanfield import MeanFieldControl as MeanFieldControl
    from chc.metrics import (
        overshoot as overshoot,
        rise_time as rise_time,
        settling_time as settling_time,
        steady_state_error as steady_state_error,
    )
    from chc.mintime import (
        bang_bang_control as bang_bang_control,
        bang_bang_rollout as bang_bang_rollout,
        BangBangResult as BangBangResult,
        double_integrator_min_time as double_integrator_min_time,
        switching_function as switching_function,
    )
    from chc.mmm import (
        adstock_dynamics as adstock_dynamics,
        MarketingMixPlant as MarketingMixPlant,
        MarketingMixSystem as MarketingMixSystem,
        MmmArm as MmmArm,
        MmmReport as MmmReport,
        run_marketing_mix as run_marketing_mix,
    )
    from chc.mpc import mpc_control as mpc_control
    from chc.network_causal import (
        ConfoundedNetworkSystem as ConfoundedNetworkSystem,
        DelayedNetworkPanel as DelayedNetworkPanel,
        estimate_network_effects as estimate_network_effects,
        estimate_network_effects_gnn as estimate_network_effects_gnn,
        estimate_propagation as estimate_propagation,
        graph_shells as graph_shells,
        kronecker_spectrum as kronecker_spectrum,
        NeighbourMessagePassing as NeighbourMessagePassing,
        panel_covariance as panel_covariance,
        torus_adjacency as torus_adjacency,
    )
    from chc.offpolicy import fit_behavior_policy as fit_behavior_policy
    from chc.panel import installed_version as installed_version
    from chc.pathway import (
        causal_pathway as causal_pathway,
        causal_pathway_certificate as causal_pathway_certificate,
        CausalPathway as CausalPathway,
        PathwayCertificate as PathwayCertificate,
        PathwayEdge as PathwayEdge,
    )
    from chc.plan import (
        CertificateStatus as CertificateStatus,
        ModulusSource as ModulusSource,
        PlanRegretBound as PlanRegretBound,
        PriceStatus as PriceStatus,
        RowPrice as RowPrice,
        SafetyCertificate as SafetyCertificate,
        ShadowPrices as ShadowPrices,
    )
    from chc.reachability import (
        backward_reachable_tube as backward_reachable_tube,
        barrier_reachability_gap as barrier_reachability_gap,
        BarrierReachabilityGap as BarrierReachabilityGap,
        higher_order_barrier_gap as higher_order_barrier_gap,
        HigherOrderBarrierGap as HigherOrderBarrierGap,
        ReachableTube as ReachableTube,
        robust_hamiltonian as robust_hamiltonian,
    )
    from chc.regret import (
        AdaptiveExplorationCurve as AdaptiveExplorationCurve,
        asymmetric_control_improvement as asymmetric_control_improvement,
        bandit_causal_certificate as bandit_causal_certificate,
        BanditCausalCurve as BanditCausalCurve,
        CappedExplorationPolicy as CappedExplorationPolicy,
        causal_vs_predictive_certificate as causal_vs_predictive_certificate,
        CausalControlCurve as CausalControlCurve,
        ce_explicit_constant_certificate as ce_explicit_constant_certificate,
        CeExplicitConstantCurve as CeExplicitConstantCurve,
        certainty_equivalence_control as certainty_equivalence_control,
        certainty_equivalence_gap as certainty_equivalence_gap,
        closed_loop_cost as closed_loop_cost,
        cluster_fold_leakage_certificate as cluster_fold_leakage_certificate,
        clustered_lower_bound_certificate as clustered_lower_bound_certificate,
        ClusteredLowerBoundCurve as ClusteredLowerBoundCurve,
        composition_transfer_certificate as composition_transfer_certificate,
        CompositionTransferCurve as CompositionTransferCurve,
        confounded_turnpike_certificate as confounded_turnpike_certificate,
        ConfoundedTurnpikeCurve as ConfoundedTurnpikeCurve,
        confounding_regret_floor_certificate as confounding_regret_floor_certificate,
        confounding_robust_control as confounding_robust_control,
        confounding_robust_control_benchmark as confounding_robust_control_benchmark,
        confounding_robust_control_certificate as confounding_robust_control_certificate,
        confounding_robust_lq_regret as confounding_robust_lq_regret,
        confounding_robust_lq_regret_certificate as confounding_robust_lq_regret_certificate,
        confounding_robust_lq_regret_matrix as confounding_robust_lq_regret_matrix,
        confounding_robust_tracking_benchmark as confounding_robust_tracking_benchmark,
        confounding_robust_tracking_loop as confounding_robust_tracking_loop,
        ConfoundingRegretFloorCurve as ConfoundingRegretFloorCurve,
        ConfoundingRobustControlCurve as ConfoundingRobustControlCurve,
        ConfoundingRobustLQRegretCurve as ConfoundingRobustLQRegretCurve,
        conjugate_time_certificate as conjugate_time_certificate,
        ConjugateTimeCurve as ConjugateTimeCurve,
        constrained_ce_regret_certificate as constrained_ce_regret_certificate,
        ConstrainedRegretCurve as ConstrainedRegretCurve,
        cross_cluster_mixing_certificate as cross_cluster_mixing_certificate,
        CrossClusterMixingCurve as CrossClusterMixingCurve,
        delayed_network_certificate as delayed_network_certificate,
        dlqr as dlqr,
        doubly_robust_control_certificate as doubly_robust_control_certificate,
        DoublyRobustCurve as DoublyRobustCurve,
        dynamic_causal_regret_certificate as dynamic_causal_regret_certificate,
        DynamicCausalCurve as DynamicCausalCurve,
        DynamicConfoundingCurve as DynamicConfoundingCurve,
        end_to_end_c2_certificate as end_to_end_c2_certificate,
        EndToEndC2Curve as EndToEndC2Curve,
        ensemble_control_certificate as ensemble_control_certificate,
        EnsembleControlCurve as EnsembleControlCurve,
        exact_matrix_ratio_moment as exact_matrix_ratio_moment,
        exact_ratio_moment as exact_ratio_moment,
        exposure_map_certificate as exposure_map_certificate,
        ExposureMapCurve as ExposureMapCurve,
        finite_horizon_pl_certificate as finite_horizon_pl_certificate,
        FiniteHorizonPLCurve as FiniteHorizonPLCurve,
        fold_exactness_certificate as fold_exactness_certificate,
        fold_heuristic_certificate as fold_heuristic_certificate,
        FoldDesign as FoldDesign,
        FoldExactnessCurve as FoldExactnessCurve,
        FoldHeuristicCurve as FoldHeuristicCurve,
        highprob_regret_certificate as highprob_regret_certificate,
        HighProbRegretCurve as HighProbRegretCurve,
        hinf_robust_regret_certificate as hinf_robust_regret_certificate,
        HInfRobustCurve as HInfRobustCurve,
        information_lower_bound_certificate as information_lower_bound_certificate,
        InformationLowerBoundCurve as InformationLowerBoundCurve,
        interference_convexity_certificate as interference_convexity_certificate,
        interference_orthogonal_certificate as interference_orthogonal_certificate,
        interference_regret_certificate as interference_regret_certificate,
        InterferenceConvexityCurve as InterferenceConvexityCurve,
        InterferenceOrthogonalCurve as InterferenceOrthogonalCurve,
        lq_regret_sensitivity as lq_regret_sensitivity,
        MarketplaceControlCurve as MarketplaceControlCurve,
        matrix_ratio_certificate as matrix_ratio_certificate,
        minimax_exploration_certificate as minimax_exploration_certificate,
        minimax_lq_certificate as minimax_lq_certificate,
        minimax_lq_policy as minimax_lq_policy,
        MinimaxAction as MinimaxAction,
        MinimaxBranch as MinimaxBranch,
        MinimaxCriterion as MinimaxCriterion,
        MinimaxLQCertificate as MinimaxLQCertificate,
        MinimaxLQPolicy as MinimaxLQPolicy,
        multichannel_control_certificate as multichannel_control_certificate,
        MultiChannelControlCurve as MultiChannelControlCurve,
        multivariate_action_floor as multivariate_action_floor,
        multivariate_interference_certificate as multivariate_interference_certificate,
        multivariate_transfer_certificate as multivariate_transfer_certificate,
        multivariate_van_trees_certificate as multivariate_van_trees_certificate,
        MultivariateActionFloor as MultivariateActionFloor,
        MultivariateInterferenceCurve as MultivariateInterferenceCurve,
        MultivariateTransferCurve as MultivariateTransferCurve,
        MultivariateVanTreesCurve as MultivariateVanTreesCurve,
        nonlinear_regret_certificate as nonlinear_regret_certificate,
        NonlinearRegretCurve as NonlinearRegretCurve,
        optimal_fold_partition as optimal_fold_partition,
        OptimalExplorationCurve as OptimalExplorationCurve,
        orthogonal_control_certificate as orthogonal_control_certificate,
        OrthogonalControlCurve as OrthogonalControlCurve,
        panel_estimator_certificate as panel_estimator_certificate,
        PanelEstimatorGate as PanelEstimatorGate,
        partial_id_control_certificate as partial_id_control_certificate,
        PartialIdControlCurve as PartialIdControlCurve,
        pessimism_variance_certificate as pessimism_variance_certificate,
        PessimismCurve as PessimismCurve,
        regret_scaling as regret_scaling,
        RegretCurve as RegretCurve,
        space_time_fold_certificate as space_time_fold_certificate,
        SpaceTimeFoldCurve as SpaceTimeFoldCurve,
        strong_convexity_regret_bound as strong_convexity_regret_bound,
        transportability_regret_certificate as transportability_regret_certificate,
        TransportabilityCurve as TransportabilityCurve,
        van_trees_certificate as van_trees_certificate,
        VanTreesCurve as VanTreesCurve,
        worst_case_asymmetric_loss as worst_case_asymmetric_loss,
    )
    from chc.residual import (
        ContractiveResidual as ContractiveResidual,
        control_affine_features as control_affine_features,
        ControlAffineResidual as ControlAffineResidual,
        convex_energy_certificate as convex_energy_certificate,
        ConvexEnergyCertificate as ConvexEnergyCertificate,
        damping_injection_certificate as damping_injection_certificate,
        DampingInjectionCertificate as DampingInjectionCertificate,
        fit_spectral_residual as fit_spectral_residual,
        GraphResidual as GraphResidual,
        KANResidual as KANResidual,
        lipschitz_certificate as lipschitz_certificate,
        LipschitzCertificate as LipschitzCertificate,
        LipschitzResidual as LipschitzResidual,
        MLPResidual as MLPResidual,
        port_hamiltonian_certificate as port_hamiltonian_certificate,
        PortHamiltonianCertificate as PortHamiltonianCertificate,
        PortHamiltonianEnergy as PortHamiltonianEnergy,
        PortHamiltonianResidual as PortHamiltonianResidual,
        spectral_residual_certificate as spectral_residual_certificate,
        SpectralResidual as SpectralResidual,
        SpectralResidualCurve as SpectralResidualCurve,
        ZeroResidual as ZeroResidual,
    )
    from chc.scm import (
        augmented_synthetic_control as augmented_synthetic_control,
        synthetic_control as synthetic_control,
        SyntheticControlResult as SyntheticControlResult,
    )
    from chc.splitting import (
        exact_linear_flow as exact_linear_flow,
        lie_trotter_step as lie_trotter_step,
        residual_flow as residual_flow,
        strang_marchuk_step as strang_marchuk_step,
    )
    from chc.support import (
        pessimistic_control as pessimistic_control,
        pessimistic_solve as pessimistic_solve,
    )
    from chc.symbolic import (
        extract_symbolic as extract_symbolic,
        extract_symbolic_edge as extract_symbolic_edge,
        kan_edge as kan_edge,
        LIBRARY as LIBRARY,
        symbolic_extraction_certificate as symbolic_extraction_certificate,
        SymbolicEdge as SymbolicEdge,
        SymbolicExtractionCurve as SymbolicExtractionCurve,
    )
    from chc.toeplitz import (
        circulant_matvec as circulant_matvec,
        circulant_operator_norm as circulant_operator_norm,
        circulant_symbol as circulant_symbol,
        gohberg_semencul_apply as gohberg_semencul_apply,
        gohberg_semencul_covariance as gohberg_semencul_covariance,
        gohberg_semencul_generators as gohberg_semencul_generators,
        levinson_durbin as levinson_durbin,
        sample_autocorrelation as sample_autocorrelation,
        solve_toeplitz as solve_toeplitz,
        toeplitz_matvec as toeplitz_matvec,
    )
    from chc.train import (
        fit_residual as fit_residual,
        fit_residual_multistep as fit_residual_multistep,
        one_step_mse as one_step_mse,
        rollout_mse as rollout_mse,
    )
    from chc.transport import (
        advection_diffusion_field as advection_diffusion_field,
        advection_diffusion_kernel as advection_diffusion_kernel,
        advection_diffusion_propagator as advection_diffusion_propagator,
        advection_diffusion_symbol as advection_diffusion_symbol,
        MeanFieldTransport as MeanFieldTransport,
        periodic_smoothing_kernel as periodic_smoothing_kernel,
        periodic_wavenumbers as periodic_wavenumbers,
        solve_transport as solve_transport,
        transport_step as transport_step,
    )
    from chc.uncertainty import (
        benchmark_gamma as benchmark_gamma,
        certified_horizon as certified_horizon,
        closed_loop_rollout_bound as closed_loop_rollout_bound,
        confounding_cost_bound_certificate as confounding_cost_bound_certificate,
        confounding_robust_certificate as confounding_robust_certificate,
        confounding_robust_closed_loop_bound as confounding_robust_closed_loop_bound,
        confounding_robust_closed_loop_certificate as confounding_robust_closed_loop_certificate,
        confounding_robust_inflation as confounding_robust_inflation,
        confounding_robust_radius as confounding_robust_radius,
        ConfoundingBoundCurve as ConfoundingBoundCurve,
        ConfoundingRobustCertificate as ConfoundingRobustCertificate,
        ConfoundingRobustClosedLoopCertificate as ConfoundingRobustClosedLoopCertificate,
        ConfoundingRobustPenalty as ConfoundingRobustPenalty,
        constraint_margin as constraint_margin,
        contractive_rollout_bound as contractive_rollout_bound,
        contractive_rollout_certificate as contractive_rollout_certificate,
        ContractiveRolloutCertificate as ContractiveRolloutCertificate,
        cvar_upper as cvar_upper,
        EnsembleResidual as EnsembleResidual,
        EnsembleUncertainty as EnsembleUncertainty,
        fit_ensemble as fit_ensemble,
        gamma_benchmark_certificate as gamma_benchmark_certificate,
        GammaBenchmark as GammaBenchmark,
        GammaBenchmarkCertificate as GammaBenchmarkCertificate,
        lipschitz_rollout_bound as lipschitz_rollout_bound,
        lipschitz_rollout_certificate as lipschitz_rollout_certificate,
        LipschitzRolloutCertificate as LipschitzRolloutCertificate,
        msm_worst_case_mean as msm_worst_case_mean,
        negative_control_gamma as negative_control_gamma,
        NestedCVaRPenalty as NestedCVaRPenalty,
        NestedRiskCertificate as NestedRiskCertificate,
        sharded_ensemble_certificate as sharded_ensemble_certificate,
        ShardedEnsembleCertificate as ShardedEnsembleCertificate,
        support_calibrated_error as support_calibrated_error,
        time_varying_rollout_bound as time_varying_rollout_bound,
        time_varying_rollout_certificate as time_varying_rollout_certificate,
        TimeVaryingRolloutCertificate as TimeVaryingRolloutCertificate,
        WassersteinPenalty as WassersteinPenalty,
    )
    # isort: on
else:

    def __getattr__(name: str) -> object:
        module = _MOVED.get(name)
        if module is None:
            raise AttributeError(f"module 'chc' has no attribute {name!r}")
        _warnings.warn(
            f"chc.{name} leaves the top level in 1.0: import it from {module}",
            DeprecationWarning,
            stacklevel=2,
        )
        return getattr(_importlib.import_module(module), name)
